### PR TITLE
NSM Uplift to 1.4.0

### PR DESCRIPTION
**Pull request by LionelJouin**
## Description
- Add NSM_LIVENESSCHECKENABLED env variable with "false" as value in the NSC container in the LB pod
- dnscontext chain element removed
- NetworkServiceEndpointRegistryClient and NetworkServiceRegistryClient adapted to the new SDK version
- NSE VLAN CIDR_PREFIX env variable adapted

`cmd-nsc:v1.4.0` and `cmd-nse-remote-vlan:v1.4.0` are on the Nordix registry.
cmd-nse-remote-vlan:v1.4.0 is compiled from this source (to include grpc-health-probe): https://github.com/Nordix/nsm-cmd-nse-remote-vlan/tree/probes

## Issue link
/

## Checklist

- Purpose
    - [ ] Bug fix
    - [x] New functionality
    - [ ] Documentation
    - [ ] Refactoring
    - [ ] CI
- Test
    - [ ] Unit test
    - [ ] E2E Test
    - [x] Tested manually
- Introduce a breaking change
    - [ ] Yes (description required)
    - [ ] No
- Introduce changes in the Operator 
    - [x] Yes (description required)
    - [ ] No

### CODE REVIEW

**Comment by zolug** [comment]
Works fine on xcluster so far.
Also, NSM accepted the PR to toggle data path healing in NSC via env var.

**Comment by uablrek** [comment]
Sumething is not right. I apply this patch, am not using the helm-charts but build with the updated `go.mod`. But my 2 load-balancers gets the same external address;
```
  07:43:53 (vm-202): TEST CASE: Collect load-balancer addresses for trench [red]
169.254.101.1
169.254.101.1
1000::1:a9fe:6501
1000::1:a9fe:6501
```
I use nsm images built on nsm/master, not any v1.4 branch, if that can cause the problem.

**Comment by uablrek** [comment]
/lgtm
All my tests work with this PR and Laszlos PR on NSM applied.
I am still unsure if this PR should be merged, or if we shall wait until v1.4.0 is released, hopefully including Laszlos PR.

**Comment by LionelJouin** [comment]
@uablrek @zolug I updated the PR to NSM Uplift to 1.4.0-rc.2
https://github.com/networkservicemesh/cmd-nsc/pull/447 has been merged and is included in it.

**Review by uablrek — APPROVED** [review]

**Review by zolug — APPROVED** [review]

**Comment by LionelJouin** [comment]
@uablrek @zolug I updated the PR to NSM Uplift to 1.4.0

**Pull request merged**
