### PR TITLE
Target scale-in, NFQLB, Ambassador instructions 

### PR DESCRIPTION
**Pull request by LionelJouin**
- Fix target scale-in 
- NFQLB updated to 0.1.1
- Ambassador demo instructions (connect/disconnect a trench, request/close a stream)

### CODE REVIEW

**Review by zolug — APPROVED** [review]

**Review by estinfra — COMMENTED** [review]
FOSS Analysis is done. Please check the [log](https://central.jenkins.est.tech/job/est-nsm-meridio-merge-foss-analysis-master/21/consoleFull).

**Pull request merged**
