### PR TITLE
NSM uplift to v1.7.0

### PR DESCRIPTION
**Pull request by LionelJouin**
## Description

https://github.com/networkservicemesh/api/releases/tag/v1.7.0
https://github.com/networkservicemesh/sdk/releases/tag/v1.7.0
https://github.com/networkservicemesh/sdk-sriov/releases/tag/v1.7.0

cmd-nsc:v1.7.0 and cmd-nse-remote-vlan:v1.7.0 are on the Nordix registry.
cmd-nse-remote-vlan:v1.7.0 is compiled from this source (to include grpc-health-probe): https://github.com/Nordix/nsm-cmd-nse-remote-vlan/tree/probes-1.7.0

NSM_REGISTRY_SERVER_POLICIES and NSM_REGISTRY_CLIENT_POLICIES are now set to "" to disable the NSE/NS registration authentication (new feature in v1.7.0 that requires changes in the NSEs to be compatible)

## Issue link

/

## Checklist

- Purpose
    - [ ] Bug fix
    - [x] New functionality
    - [ ] Documentation
    - [ ] Refactoring
    - [ ] CI
- Test
    - [ ] Unit test
    - [ ] E2E Test
    - [ ] Tested manually
- Introduce a breaking change
    - [ ] Yes (description required)
    - [x] No
- Introduce changes in the Operator 
    - [ ] Yes (description required)
    - [x] No

### CODE REVIEW

**Comment by LionelJouin** [comment]
After checking with the NSM community, the new version has a NBC, so previous Meridio version cannot be used with v1.7.0-rc.1. NSM fix might come with rc-2. 
I fixed the NBC with this commit: https://github.com/Nordix/Meridio/pull/338/commits/7b50b1032984cf659f95a777838a0a2543723d8a, this PR can now be compiled and will work fine with v1.7.0-rc.1.
I haven't yet tried the Meridio version from this current PR + NSM 1.6.1 or older. 

There might be a problem with the VLAN mechanism, the stateless-lb-frontend seems to take more time to be fully ready, and it seems when the vlan interface is created, pinging the neighbors doesn't work the first 1 or 2 minutes.

**Comment by LionelJouin** [comment]
## v1.7.0-rc.1 -> v1.7.0-rc.2

NBC due to NS/NSE registration authentication can now be disabled with these parameters: https://github.com/networkservicemesh/cmd-nsmgr/blob/release/v1.7.0-rc.2/internal/config/config.go#L31-L32
The VLAN issue is tracked in: https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/781
v1.7.0-rc.1 is now in this branch https://github.com/Nordix/Meridio/tree/nsm-uplift-v1.7.0-rc.1

## Original description

https://github.com/networkservicemesh/api/releases/tag/v1.7.0-rc.1
https://github.com/networkservicemesh/sdk/releases/tag/v1.7.0-rc.1
https://github.com/networkservicemesh/sdk-sriov/releases/tag/v1.7.0-rc.1

cmd-nsc:v1.7.0-rc.1 and cmd-nse-remote-vlan:v1.7.0-rc.1 are on the Nordix registry.
cmd-nse-remote-vlan:v1.7.0-rc.1 is compiled from this source (to include grpc-health-probe): https://github.com/Nordix/nsm-cmd-nse-remote-vlan/tree/probes-1.7.0-rc.1

The uplift doesn't work, I suspect the NSE registration to fail. Here is some errors I get (in nsmgr):
```
2022-12-13T13:34:35.658739801Z stderr F Dec 13 13:34:35.658[37m [TRAC] [type:registry] [0m(3.1)     register={"name":"conduit-a.trench-a.red","payload":"ETHERNET","path_ids":["","spiffe://example.org/ns/nsm/sa/nsmgr-sa"]}
2022-12-13T13:34:35.658749897Z stderr F Dec 13 13:34:35.658[31m [ERRO] [type:registry] [0m(3.2)     failed to parse jwt token: token contains an invalid number of segments
2022-12-13T13:34:35.658753233Z stderr F Dec 13 13:34:35.658[31m [ERRO] [type:registry] [0m(2.4)    failed to parse jwt token: token contains an invalid number of segments
2022-12-13T13:34:35.658755497Z stderr F Dec 13 13:34:35.658[31m [ERRO] [type:registry] [0m(1.2)   failed to parse jwt token: token contains an invalid number of segments
```

```
2022-12-13T13:33:09.233691688Z stderr F Dec 13 13:33:09.233[37m [TRAC] [type:registry] [0m(2.1)    register={"name":"proxy.conduit-a.trench-a.red","payload":"ETHERNET","matches":[{"source_selector":{"nodeName":"{{.nodeName}}"},"routes":[{"destination_selector":{"nodeName":"{{.nodeName}}"}}]}]}
2022-12-13T13:33:09.233740985Z stderr F Dec 13 13:33:09.233[33m [WARN] [type:registry] [0m(2.2)    an error during getting peer token from the context: values of 'nsm-client-token' has wrong length 0, expected 1;	github.com/networkservicemesh/sdk/pkg/tools/token.getSingleValue;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/tools/token/context.go:66;	github.com/networkservicemesh/sdk/pkg/tools/token.FromContext;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/tools/token/context.go:41;	github.com/networkservicemesh/sdk/pkg/registry/common/updatepath.(*updatePathNSServer).Register;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/registry/common/updatepath/ns_server.go:49;	github.com/networkservicemesh/sdk/pkg/registry/core/trace.(*traceNetworkServiceRegistryServer).Register;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/registry/core/trace/ns_registry.go:128;	github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceRegistryServer).Register;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/registry/core/next/ns_registry_server.go:59;	github.com/networkservicemesh/sdk/pkg/registry/common/grpcmetadata.(*grpcMetadataNSServer).Register;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/registry/common/grpcmetadata/ns_server.go:54;	github.com/networkservicemesh/sdk/pkg/registry/core/trace.(*traceNetworkServiceRegistryServer).Register;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/registry/core/trace/ns_registry.go:128;	github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceRegistryServer).Register;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/registry/core/next/ns_registry_server.go:59;	github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceRegistryServer).Register;		/go/pkg/mod/github.com/networkservicemesh/sdk@v1.7.0-rc.1/pkg/registry/core/next/ns_registry_server.go:59;	github.com/networkservicemesh/api/pkg/api/registry._NetworkServiceRegistry_Register_Handler;		/go/pkg/mod/github.com/networkservicemesh/api@v1.7.0-rc.1/pkg/api/registry/registry.pb.go:1296;	google.golang.org/grpc.(*Server).processUnaryRPC;		/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301;	google.golang.org/grpc.(*Server).handleStream;		/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642;	google.golang.org/grpc.(*Server).serveStreams.func1.2;		/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938;	runtime.goexit;		/usr/local/go/src/runtime/asm_amd64.s:1571;	
2022-12-13T13:33:09.2337844Z stderr F Dec 13 13:33:09.233[33m [WARN] [type:registry] [0m(2.3)    an error during parsing peer token: <nil>
```

I tried NSM v1.7.0-rc.1 with Meridio v1.0.0. The NSC in the stateless-lb-frontend won't connect to the vlan NS.

**Comment by LionelJouin** [comment]
| meridio | NSM | status |
| ----------- | ----------- | ----------- |
| v1.7.0-rc.2 uplift (this PR) | v1.7.0-rc.2 | Works |
| v1.0.0.0 | v1.7.0-rc.2 | doesn't work: NSE can't register NSE (executing phase 6: register nse with nsm) |
| v1.7.0-rc.2 uplift (this PR)  | v1.6.1 | ? |

**Comment by uablrek** [comment]
Run Meridio with this PR applied and NSM v1.6.1 works if `NSM_REGISTRY_CLIENT_POLICIES=""` is set for the `cmd-nse-remote-vlan:v1.7.0-rc.3` container.

**Comment by uablrek** [comment]
Meaning that upgrade of Meridio while maintaining the old NSM should be possible, as long as the `NSM_REGISTRY_CLIENT_POLICIES` variable is part of the upgrade of the nse-remote-vlan.
```yaml
      containers:
        - name: nse
          image: ghcr.io/networkservicemesh/cmd-nse-remote-vlan:v1.7.0-rc.3
          imagePullPolicy: IfNotPresent
          env:
            - name: NSM_REGISTRY_CLIENT_POLICIES
              value: ""
```
Tested with forwarder vpp and ovs and multus (without the nse).

**Comment by LionelJouin** [comment]
I just added it to the helm chart if you are still using it @uablrek.
I tried the example nse-remote-vlan, and I have the same problem when using NSE v1.6.1 and NSM v1.7.0-rc.1

**Comment by LionelJouin** [comment]
Now everything seems to work fine.

**Comment by uablrek** [comment]
I made a test to upgrade nsm v1.6.1 -> v1.7.0-rc.3 with ctraffic running. I works, but gives a ~2m outage.

**Comment by johlj** [comment]
Hi,

could the outage be due to this?
 https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/781

Br,
Johan

**Comment by uablrek** [comment]
Changed to nsm v1.7.0 and rebase with master. Upgrade of nsm v1.6.1 -> v1.7.0 with Meridio 1.0.0 does **not** seem to work.

**Comment by uablrek** [comment]
Upgrade of nsm v1.6.1 -> v1.7.0 with Meridio 1.0.0 works now. I missed that env vars for registry-k8s have changed names; `REGISTRY_K8S_* -> NSM_*`. There is no similar change in registry-memory. Still the outage though.

**Comment by uablrek** [comment]
The ~2m outage on upgrade is caused by connectivity fail between load-balancer and targets. Ping from the lb-pods to the targets fails. I have not tested if proxy-target communication works.

**Comment by uablrek** [comment]
Upgrade v1.6.1 -> v1.7.0 fails with forwarder-ovs. The problem is similar to the outage above, but connectivity never recovers. All PODs are OK.

**Comment by LionelJouin** [comment]
v1.7.0-rc.3 is now in this branch https://github.com/Nordix/Meridio/tree/nsm-uplift-v1.7.0-rc.3

**Comment by LionelJouin** [comment]
Tried it and it worked fine, I re-arranged the commits. 
The downtime during the NSM upgrade is expected and was already there before.

**Comment by LionelJouin** [comment]
Seems there will be a v1.7.1: https://github.com/networkservicemesh/api/releases/tag/v1.7.1-rc.1

**Comment by uablrek** [comment]
Seems to be IPSec. Do we need/want it?

**Comment by LionelJouin** [comment]
From the community meeting it seems it is due to expiration and timeout bug (which was also existing in v1.6), so I think yes, we might want it.

**Comment by uablrek** [comment]
I have tested v1.7.0 (this PR in it's current form) with KinD and xcluster, including upgrade of NSM v1.6.0 -> v1.7.0 with Meridio built on the `nsm-uplift` branch and everything seem to work. I hold my review answer to v1.7.1 then?

**Comment by uablrek** [comment]
Will we upgrade v1.6.1 -> v1.7.1 directly, or jump via v1.7.0 (which seems unnecessary)?

**Pull request merged**
