### PR TITLE
Runtime configuration

### LINKED ISSUE #8: Runtime configuration framework
Adding the framework for runtime configuration

### PR DESCRIPTION
**Pull request by LionelJouin**
Fix #8

### CODE REVIEW

**Review by estinfra — COMMENTED** [review]
FOSS Analysis is done. Please check the [log](https://central.jenkins.est.tech/job/est-nsm-meridio-merge-foss-analysis-master/8/consoleFull).

**Review by estinfra — COMMENTED** [review]
FOSS Analysis is done. Please check the [log](https://central.jenkins.est.tech/job/est-nsm-meridio-merge-foss-analysis-master/10/consoleFull).

**Comment by fdegir** [comment]
Apologies for the noise. Troubleshooting a certificate issue on EST ARM.

**Review by estinfra — COMMENTED** [review]
FOSS Analysis is done. Please check the [log](https://central.jenkins.est.tech/job/est-nsm-meridio-merge-foss-analysis-master/11/consoleFull).

**Review by estinfra — COMMENTED** [review]
FOSS Analysis is done. Please check the [log](https://central.jenkins.est.tech/job/est-nsm-meridio-merge-foss-analysis-master/15/consoleFull).

**Pull request merged**
