### PR TITLE
Dual Stack Support

### LINKED ISSUE #13: Add dualstack support
Add dualstack support for the Meridio elements

### PR DESCRIPTION
**Pull request by LionelJouin**
Fix #13

### CODE REVIEW

**Comment by fdegir** [comment]
/reverify

source .profile in Jenkins job to ensure PATH is correct.

**Review by estinfra — COMMENTED** [review]
FOSS Analysis is done. Please check the [log](https://central.jenkins.est.tech/job/est-nsm-meridio-merge-foss-analysis-master/4/consoleFull).

**Pull request merged**
